services:
  frontend:
    image: wutipong/gallery4-frontend:latest
    environment: 
      BACKEND_URL: backend:8080
    depends_on:
      - backend
    
  backend:
    image: wutipong/gallery4-backend:latest
    environment:
      DATA_DIR: /data
    volumes:
      - ${DATA_PATH-./data}:/data:ro
    
  caddy:
    image: caddy:alpine
    # restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "${HTTP_PORT-8000}:80"
    volumes:
      - ./caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: